export const AUTH_ERROR_CODES = {
  INVALID_GOOGLE_TOKEN: 'INVALID_GOOGLE_TOKEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];

export const AUTH_IDENTITY_KIND = {
  GUEST: 'guest',
  AUTHENTICATED: 'authenticated',
} as const;