export const ERROR_CODES = {
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CARD_NOT_FOUND: 'CARD_NOT_FOUND',
  PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  MISSING_FILTER: 'MISSING_FILTER',
  INVALID_PARAMETER: 'INVALID_PARAMETER',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];